<?php
/**
 * EmailAnalysisTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailSlurpSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailSlurp API
 *
 * For extensive guides and examples see [full documentation](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support).
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: jackmahoney212@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailSlurpSDK;

/**
 * EmailAnalysisTest Class Doc Comment
 *
 * @category    Class
 * @description Analysis of email
 * @package     MailSlurpSDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailAnalysisTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailAnalysis"
     */
    public function testEmailAnalysis()
    {
    }

    /**
     * Test attribute "dkim_verdict"
     */
    public function testPropertyDkimVerdict()
    {
    }

    /**
     * Test attribute "dmarc_verdict"
     */
    public function testPropertyDmarcVerdict()
    {
    }

    /**
     * Test attribute "spam_verdict"
     */
    public function testPropertySpamVerdict()
    {
    }

    /**
     * Test attribute "spf_verdict"
     */
    public function testPropertySpfVerdict()
    {
    }

    /**
     * Test attribute "virus_verdict"
     */
    public function testPropertyVirusVerdict()
    {
    }
}
