<?php
/**
 * CommonOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailSlurpSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailSlurp API
 *
 * For extensive guides and examples see [full documentation](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support).
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: jackmahoney212@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MailSlurpSDK;

use \MailSlurpSDK\Configuration;
use \MailSlurpSDK\ApiException;
use \MailSlurpSDK\ObjectSerializer;

/**
 * CommonOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailSlurpSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CommonOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNewEmailAddressUsingPOST
     *
     * Create new email address.
     *
     */
    public function testCreateNewEmailAddressUsingPOST()
    {
    }

    /**
     * Test case for fetchLatestEmailUsingGET
     *
     * Fetch inbox's latest email or if empty wait for email to arrive.
     *
     */
    public function testFetchLatestEmailUsingGET()
    {
    }

    /**
     * Test case for sendEmailSimpleUsingPOST
     *
     * Send an email from a random email address.
     *
     */
    public function testSendEmailSimpleUsingPOST()
    {
    }
}
