<?php
/**
 * ExtraOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailSlurpSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailSlurp API
 *
 * For extensive guides and examples see [full documentation](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support).
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: jackmahoney212@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MailSlurpSDK;

use \MailSlurpSDK\Configuration;
use \MailSlurpSDK\ApiException;
use \MailSlurpSDK\ObjectSerializer;

/**
 * ExtraOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailSlurpSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExtraOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bulkCreateInboxesUsingPOST
     *
     * Bulk create Inboxes (email addresses).
     *
     */
    public function testBulkCreateInboxesUsingPOST()
    {
    }

    /**
     * Test case for bulkDeleteInboxesUsingDELETE
     *
     * Bulk Delete Inboxes.
     *
     */
    public function testBulkDeleteInboxesUsingDELETE()
    {
    }

    /**
     * Test case for bulkSendEmailsUsingPOST
     *
     * Bulk Send Emails.
     *
     */
    public function testBulkSendEmailsUsingPOST()
    {
    }

    /**
     * Test case for createInboxUsingPOST
     *
     * Create an Inbox (email address).
     *
     */
    public function testCreateInboxUsingPOST()
    {
    }

    /**
     * Test case for deleteEmailUsingDELETE
     *
     * Delete Email.
     *
     */
    public function testDeleteEmailUsingDELETE()
    {
    }

    /**
     * Test case for deleteInboxUsingDELETE
     *
     * Delete Inbox.
     *
     */
    public function testDeleteInboxUsingDELETE()
    {
    }

    /**
     * Test case for getEmailUsingGET
     *
     * Get Email Content.
     *
     */
    public function testGetEmailUsingGET()
    {
    }

    /**
     * Test case for getEmailsUsingGET
     *
     * List an Inbox's Emails.
     *
     */
    public function testGetEmailsUsingGET()
    {
    }

    /**
     * Test case for getInboxUsingGET
     *
     * Get Inbox.
     *
     */
    public function testGetInboxUsingGET()
    {
    }

    /**
     * Test case for getInboxesUsingGET
     *
     * List Inboxes.
     *
     */
    public function testGetInboxesUsingGET()
    {
    }

    /**
     * Test case for getRawEmailUsingGET
     *
     * Get Raw Email Content.
     *
     */
    public function testGetRawEmailUsingGET()
    {
    }

    /**
     * Test case for sendEmailUsingPOST
     *
     * Send Email.
     *
     */
    public function testSendEmailUsingPOST()
    {
    }
}
